# Generated by Django 3.0.7 on 2020-11-10 02:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_auto_20201109_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhos',
            name='referencias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
    ]
